# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0368fda6956f897363c050739649170d9ead7c3aea9723df4186d4ff7c619685d08e1b672be753cf7f290c7a9d78e64f02e02fd844e89eee82b630d3013c4bb

test:
  secret_key_base: 288d5fc206fb5dc7cf1a9ff98bc3a26be613f3532bbad3b15033d7b164fa9190abcc653b0458adb52bf7c3351a538d6dbf49bf7166904074aebb72696cfce2c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
